# Generated by Django 5.2.4 on 2025-07-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0004_remove_evenement_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("opportunites", "Opportunités d'affaires"),
                    ("networking", "Networking"),
                    ("formation", "Formation"),
                    ("conference", "Conférence"),
                    ("atelier", "Atelier"),
                ],
                max_length=50,
            ),
        ),
    ]
