# Generated by Django 5.2.4 on 2025-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0005_alter_evenement_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentation",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("commerciale", "Commerciale"),
                    ("juridique", "Juridique"),
                    ("technique", "Technique"),
                    ("autre", "Autre"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="lien",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentation",
            name="titre",
            field=models.CharField(max_length=255),
        ),
    ]
