# Generated by Django 5.2.4 on 2025-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0007_alter_annonce_categorie"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
