# Generated by Django 5.2.4 on 2025-07-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0008_annonce_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annonce",
            name="pieces_jointes",
        ),
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="annonces/")),
                (
                    "annonce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_jointes",
                        to="Affaires.annonce",
                    ),
                ),
            ],
        ),
    ]
