# Generated by Django 5.2.4 on 2025-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0009_remove_annonce_pieces_jointes_piecejointe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="evenement",
            name="tags",
        ),
        migrations.AddField(
            model_name="evenement",
            name="tags",
            field=models.ManyToManyField(blank=True, to="Affaires.tag"),
        ),
    ]
