# Generated by Django 5.2.4 on 2025-08-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0010_tag_remove_evenement_tags_evenement_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="lien_inscription",
            field=models.URLField(blank=True, null=True),
        ),
    ]
