# Generated by Django 5.2.4 on 2025-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0011_evenement_lien_inscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentation",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
