# Generated by Django 5.2.4 on 2025-08-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0012_documentation_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentation",
            name="description",
        ),
    ]
