# Generated by Django 5.2.4 on 2025-08-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0013_remove_documentation_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="annonce",
            name="lieu",
            field=models.CharField(default="Non spécifié", max_length=100),
        ),
    ]
