# Generated by Django 5.2.4 on 2025-08-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0014_annonce_lieu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publicite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("contenu", models.TextField()),
                ("badge", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="publicites/"),
                ),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                ("contact", models.CharField(max_length=100)),
            ],
        ),
    ]
