# Generated by Django 5.2.4 on 2025-08-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0015_publicite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicite",
            name="description",
        ),
    ]
