# Generated by Django 5.2.4 on 2025-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Affaires", "0016_remove_publicite_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicite",
            name="lien",
            field=models.URLField(blank=True, null=True),
        ),
    ]
